# Generated by Django 5.1.6 on 2025-02-20 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0003_achievement_created_groupmembership_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loregroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
