# Generated by Django 5.1.6 on 2025-02-21 02:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0004_loregroup_members_delete_groupmembership'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loregroup',
            managers=[
                ('groups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='loregroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
