# Generated by Django 5.1.6 on 2025-03-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0006_alter_quote_managers_alter_loregroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore.loregroup'),
        ),
    ]
