# Generated by Django 5.1.6 on 2025-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0008_loregroup_avatar_loreuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image_url',
            field=models.ImageField(null=True, upload_to='achievement_images'),
        ),
    ]
