# Generated by Django 5.1.6 on 2025-03-03 16:03

import lore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0009_alter_achievement_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loreuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=lore.models.PathAndRename('avatars')),
        ),
    ]
