# Generated by Django 5.1.6 on 2025-03-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0011_alter_achievement_image_url_alter_image_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='descrption',
            new_name='description',
        ),
    ]
