# Generated by Django 5.1.6 on 2025-03-05 01:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0012_rename_descrption_image_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('images', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
