# Generated by Django 5.1.6 on 2025-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0014_alter_image_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
