# Generated by Django 5.1.6 on 2025-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0015_alter_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='image_url',
            new_name='image',
        ),
    ]
