# Generated by Django 5.1.6 on 2025-03-06 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0017_alter_achievement_managers_alter_achievement_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loregroup',
            name='members',
            field=models.ManyToManyField(related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
