# Generated by Django 5.1.6 on 2025-03-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0018_alter_loregroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
