# Generated by Django 5.1.7 on 2025-12-03 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0020_loregroup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='context',
            field=models.TextField(default='', max_length=2048, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
