# Generated by Django 5.1.7 on 2025-11-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0021_challenge_challengeparticipant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='lore_user',
            new_name='loreuser',
        ),
    ]
