# Generated by Django 5.1.7 on 2025-11-23 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0022_rename_lore_user_challengeparticipant_loreuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='loreuser',
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='lore_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loreuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
