# Generated by Django 5.1.7 on 2025-11-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0023_remove_challengeparticipant_loreuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipant',
            name='lore_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
