# Generated by Django 5.1.7 on 2025-12-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0021_quote_context'),
        ('lore', '0024_alter_challengeparticipant_lore_user'),
    ]

    operations = [
    ]
