# Generated by Django 5.1.7 on 2026-02-02 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0025_merge_20251205_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.TextField(default='', max_length=2048, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
